<a href="https://colab.research.google.com/github/yuigit-hub/-PyTorch-learning-log/blob/main/00_Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00.Pytorch_fundamentals.ipynb

Course materials online: https://www.learnpytorch.io/00_pytorch_fundamentals/

Code: https://github.com/mrdbourke/pytorch-deep-learning

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


!nvidia-smi


###Creating tensors





In [4]:
scalar = torch.tensor(10)
scalar

tensor(10)

In [5]:
# prompt: scalar.nidm

scalar.ndim

0

In [6]:
scalar.item()


10

In [7]:
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]


tensor([7, 8])

In [13]:
a = torch.Size([2, 2])
a

torch.Size([2, 2])

In [14]:
TENSOR = torch.tensor([[[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]]],)
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
random_tensor = torch.rand(2, 3, 4)
print(random_tensor)

tensor([[[0.0288, 0.3017, 0.7137, 0.2478],
         [0.9251, 0.3194, 0.8173, 0.2523],
         [0.0573, 0.3800, 0.1033, 0.2933]],

        [[0.8157, 0.2361, 0.7306, 0.3815],
         [0.7762, 0.5808, 0.1121, 0.5796],
         [0.3701, 0.5894, 0.7740, 0.4445]]])


In [19]:
random_tensor.ndim

3

In [20]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor

tensor([[[0.7102, 0.6273, 0.6358,  ..., 0.1494, 0.7579, 0.8229],
         [0.1230, 0.0141, 0.4240,  ..., 0.8959, 0.3663, 0.3408],
         [0.6978, 0.9221, 0.0467,  ..., 0.8722, 0.4970, 0.1847],
         ...,
         [0.6955, 0.5979, 0.7052,  ..., 0.2463, 0.4288, 0.1828],
         [0.0781, 0.6620, 0.2090,  ..., 0.6485, 0.7485, 0.5174],
         [0.2058, 0.3415, 0.7938,  ..., 0.7963, 0.9879, 0.3317]],

        [[0.9442, 0.1262, 0.5528,  ..., 0.2060, 0.0428, 0.2877],
         [0.4276, 0.5124, 0.4928,  ..., 0.9508, 0.1269, 0.9409],
         [0.6748, 0.0786, 0.4801,  ..., 0.4129, 0.8844, 0.0098],
         ...,
         [0.3366, 0.0655, 0.0896,  ..., 0.9732, 0.9632, 0.0710],
         [0.7612, 0.3689, 0.9010,  ..., 0.9444, 0.7255, 0.6321],
         [0.7255, 0.1360, 0.6407,  ..., 0.8604, 0.2654, 0.6275]],

        [[0.6464, 0.4535, 0.8606,  ..., 0.2918, 0.3500, 0.5871],
         [0.8868, 0.3509, 0.9839,  ..., 0.1542, 0.0267, 0.7221],
         [0.4840, 0.2525, 0.4714,  ..., 0.5922, 0.9898, 0.

# ZERO AND ONES

In [21]:
zero = torch.zeros(3, 4, 3)
zero

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [22]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
zero.dtype

torch.float32

# Creating a range of tensors and tensor-like

In [25]:
torch.arange(0, 10)
one_to_ten = torch.arange(start=0, end=1000, step=50)
one_to_ten

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [26]:
# Creating tensor-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes







In [27]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [28]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2068, 0.4934, 0.7740, 0.7541],
        [0.2384, 0.0640, 0.9026, 0.1915],
        [0.4801, 0.7289, 0.5423, 0.0359]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [29]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [31]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [32]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([-90, -80, -70])

In [33]:
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([-9, -8, -7]) * tensor([-9, -8, -7])
Equals: tensor([81, 64, 49])
